// Copy this config to config.js
const DISCORD_APP_CLIENT_ID 		= "";
const DISCORD_BOT_MASTER_SERVER_ID 	= "";
const DISCORD_BOT_TOKEN 			= "";
const DISCORD_BOT_USERNAME 			= "Coverage Bot";
const IMPRESSLIST_URL 				= "";
const IMPRESSLIST_API_KEY 			= "";
const EC2_SERVER 					= "";

module.exports = {
	DISCORD_APP_CLIENT_ID,
	DISCORD_BOT_MASTER_SERVER_ID,
	DISCORD_BOT_TOKEN,
	DISCORD_BOT_USERNAME,
	IMPRESSLIST_URL,
	IMPRESSLIST_API_KEY,
	EC2_SERVER
};
